"""Generates src/design-system/icons/{glyphs,components}.tsx from the icon catalogue.

Run: python3 scripts/dev/gen-icons.py  (catalogue: scripts/dev/icons.py)
Existing glyphs from components/Icon/Icon.tsx are kept unchanged.
"""
import re, sys, importlib.util, pathlib

root = pathlib.Path(__file__).resolve().parents[2]
catalogue = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
spec = importlib.util.spec_from_file_location('icons', catalogue / 'icons.py')
mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)

# Keep already-published drawings: read them from the generated file (or the
# original Icon.tsx before the first generation).
generated = root / 'src/design-system/icons/glyphs.tsx'
if generated.exists():
    icon_src = generated.read_text()
    block = icon_src[icon_src.index('export const glyphs'):]
else:
    icon_src = (root / 'src/design-system/components/Icon/Icon.tsx').read_text()
    block = icon_src[icon_src.index('const paths'):]
block = block[block.index('{') + 1: block.index('\n}')]
existing = {}
for m in re.finditer(r"^\s+'?([a-z-]+)'?: (.*),$", block, re.M):
    existing[m.group(1)] = m.group(2)

TAGS = {'circle': 'Circle', 'line': 'Line', 'polyline': 'Polyline', 'polygon': 'Polygon', 'path': 'Path',
        'rect': 'Rect', 'ellipse': 'Ellipse', 'g': 'G'}

def camel(a):
    return re.sub(r'-([a-z])', lambda m: m.group(1).upper(), a)

def to_jsx(svg):
    svg = svg.replace('fill="var(--bgc)"', 'fill="currentColor"')
    def tag(m):
        close, name, attrs, selfclose = m.group(1), m.group(2), m.group(3), m.group(4)
        attrs = re.sub(r'([a-z-]+)="', lambda a: camel(a.group(1)) + '="', attrs)
        return f'<{close}{TAGS[name]}{attrs}{" /" if selfclose else ""}>'
    out = re.sub(r'<(/?)([a-z]+)([^>]*?)\s*(/?)>', tag, svg)
    count = len(re.findall(r'<[A-Z]', out))
    return out if count == 1 else f'<>{out}</>'

CAT_KEYS = {'Navigation & arrows': 'navigation', 'Actions': 'actions', 'Status & alerts': 'status', 'Settings & system': 'settings',
            'Users & people': 'users', 'Finance & banking': 'finance', 'Commerce': 'commerce', 'Files & documents': 'files',
            'Communication': 'communication', 'Security & access': 'security', 'Time, place & travel': 'time', 'Media': 'media'}

lines, cats, seen = [], [], []
for cat, items in mod.CATEGORIES.items():
    names = []
    lines.append(f'  // {cat}')
    for name, svg in items.items():
        jsx = existing.get(name) or to_jsx(svg)
        key = f"'{name}'" if '-' in name else name
        lines.append(f'  {key}: {jsx},')
        names.append(name); seen.append(name)
    cats.append(f"  {CAT_KEYS[cat]}: [{', '.join(repr(n) for n in names)}],")
missing = set(existing) - set(seen)
assert not missing, missing
used = sorted({t for t in TAGS.values() if re.search(rf'<{t}\b', '\n'.join(lines))})

glyphs = f'''// Generated by scripts/dev/gen-icons.py. Edit the catalogue, then regenerate.
import React from 'react';
import {{ {', '.join(used)} }} from 'react-native-svg';

/** Built-in glyphs drawn on a 24×24 grid with a 2px round stroke. */
export const glyphs = {{
{chr(10).join(lines)}
}} satisfies Record<string, React.ReactNode>;

export type BuiltInIconName = keyof typeof glyphs;

/** Icon names grouped by category, e.g. for icon pickers or settings screens. */
export const iconCategories = {{
{chr(10).join(cats)}
}} as const satisfies Record<string, readonly BuiltInIconName[]>;

export type IconCategory = keyof typeof iconCategories;
'''
(root / 'src/design-system/icons/glyphs.tsx').write_text(glyphs)

def pascal(n):
    return ''.join(p.capitalize() for p in n.split('-')) + 'Icon'

comps = ['// Generated by scripts/dev/gen-icons.py. One component per built-in icon.',
         "import { createIcon } from './createIcon';", '']
for n in seen:
    comps.append(f"export const {pascal(n)} = createIcon('{n}');")
(root / 'src/design-system/icons/components.tsx').write_text('\n'.join(comps) + '\n')
print(len(seen), 'icons;', len(existing), 'kept from Icon.tsx')
